name: Run Linting
on:
  push:
    branches: 
      # https://docs.renovatebot.com/key-concepts/automerge/#branch-vs-pr-automerging
      - "renovate/**" # branches Renovate creates
  pull_request:
    branches: [master]
  merge_group:
    types: [checks_requested]
    branches: [master]
  workflow_dispatch:
    inputs:
      runners:
        description: "Runners to test on"
        type: choice
        options:
          - "ubuntu-latest"
          - "self-hosted"
        default: "self-hosted"

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/.singularity
  NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # renovate: datasource=github-releases depName=nextflow/nextflow versioning=semver
  NXF_VER: "25.04.8"

jobs:
  pre-commit:
  # There are 3 run options (runner that is provided or ubuntu-latest or self-runner. As we do not have self-runner ubuntu latest is choice)
    runs-on: ${{ github.event.inputs.runners || github.run_number > 1 && 'ubuntu-latest' || 'self-hosted' }} 
    steps:
      # This is action which is used to clone our repository 
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Run prek
        # This is simillar to pre-commit hook and it checks some basic things (end of files, trailing whitespaces...) 
        uses: j178/prek-action@91fd7d7cf70ae1dee9f4f44e7dfa5d1073fe6623 # v1

  ###################
  # nf-core linting #
  ###################
  # TODO Move these to pre-commit
  # https://github.com/nf-core/tools/pull/3141

  # This action contains a couple of jobs so we will analyze it. Generally it just checks if some change happened between two commits and get module names
  nf-core-changes:
    name: nf-core-changes
    # Here we define self-hosted machine. I think we should think about how to define it and if it is suitable
    runs-on:
      - runs-on=${{ github.run_id }}-nf-core-changes
      - runner=4cpu-linux-x64
      - image=ubuntu22-full-x64
    outputs:
      # https://github.com/dorny/paths-filter?tab=readme-ov-file#custom-processing-of-changed-files
      modules: ${{ steps.filter.outputs.modules }}
      modules_files: ${{ steps.module_names.outputs.result }}
      subworkflows: ${{ steps.filter.outputs.subworkflows }}
      subworkflows_files: ${{ steps.subworkflow_names.outputs.result }}
    steps:
      # First step to clean workspace
      - name: Clean workspace
        run: |
          sudo rm -rf ./* || true
          sudo rm -rf ./.* || true
      # To clone the repository. 
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          # Used to retrieve last 2 commits
          fetch-depth: 2 # To retrieve the preceding commit. 

      # This action is used to check file changes between two commits. This is why we defined fetch-depth in the previous step
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: filter
        with:
          filters: |
            modules:
              - added|modified: 'modules/nf-core/**'
            subworkflows:
              - added|modified: 'subworkflows/nf-core/**'
          token: ""
          list-files: "json"

      # This is an action which uses custom JS to get the module names 
      - name: Get module name
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        id: module_names
        with:
          script: |
            return [...new Set(${{ steps.filter.outputs.modules_files }}
              .filter(x => x.endsWith('main.nf') || x.endsWith('.nf.test.snap'))
              .map(path => path
                .replace('modules/nf-core/', '')
                .replace(/\/(main\.nf|tests\/.*)$/, '')
              )
            )];

      # Generally we need to think if we need subworkflow 
      - name: Get subworkflow name
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        id: subworkflow_names
        with:
          script: |
            return [...new Set(${{ steps.filter.outputs.subworkflows_files }}
              .filter(x => x.endsWith('main.nf') || x.endsWith('.nf.test.snap'))
              .map(path => path
                .replace('subworkflows/nf-core/', '')
                .replace(/\/(main\.nf|tests\/.*)$/, '')
              )
            )];

      # just to echo module names. We can think to remove this step
      - name: debug
        run: |
          echo ${{ steps.filter.outputs.modules_files }}
          echo ${{ steps.module_names.outputs.result }}
          echo ${{ steps.filter.outputs.subworkflows_files }}
          echo ${{ steps.subworkflow_names.outputs.result }}

  nf-core-lint-modules:
    # again self-hosted machine. Discuss it
    runs-on:
      - runs-on=${{ github.run_id }}-nf-core-lint-modules
      - runner=4cpu-linux-x64
      - image=ubuntu22-full-x64
    name: nf-core lint modules
    # Here firstly checks if there is any output of the previous step
    needs: nf-core-changes
    if: ${{ needs.nf-core-changes.outputs.modules_files != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJson(needs.nf-core-changes.outputs.modules_files || '[]') }}
    
    # Again we clean workspace 
    steps:
      - name: Clean workspace
        run: |
          sudo rm -rf ./* || true
          sudo rm -rf ./.* || true
      # Clone repository
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      
      - name: Set up Python
        # Install python 3.14
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
        with:
          python-version: "3.14"
      # Installs cache for pip. And runner.os is used to give cache unique name per OS (Linux, Windows...)
      - uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Install pip
        # Installs pip 
        run: python -m pip install --upgrade pip

      # Action which installs java
      - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5
        with:
          distribution: "temurin"
          java-version: "17"

      # Action which installs nextflow
      - name: Set up Nextflow
        uses: nf-core/setup-nextflow@v2

      # Action which installs nf-core tools 
      - name: Install nf-core tools development version
        run: python -m pip install --upgrade --force-reinstall git+https://github.com/nf-core/tools.git@dev

      # Action which runs nf-core modules lint command on the specified module 
      - name: Lint module ${{ matrix.module }}
        run: nf-core modules lint ${{ matrix.module }}

  # Think about that. Anyway it will be skipped so we can keep it
  nf-core-lint-subworkflows:
    runs-on:
      - runs-on=${{ github.run_id }}-nf-core-lint-subworkflows
      - runner=4cpu-linux-x64
      - image=ubuntu22-full-x64
    name: nf-core lint subworkflows
    needs: nf-core-changes
    if: ${{ needs.nf-core-changes.outputs.subworkflows_files != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        subworkflow: ${{ fromJson(needs.nf-core-changes.outputs.subworkflows_files || '[]') }}
    steps:
      - name: Clean workspace
        run: |
          sudo rm -rf ./* || true
          sudo rm -rf ./.* || true
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
        with:
          python-version: "3.14"

      - name: Set up Nextflow
        uses: nf-core/setup-nextflow@v2

      - name: Install nf-core tools development version
        run: python -m pip install --upgrade --force-reinstall git+https://github.com/nf-core/tools.git@dev

      - name: Lint subworkflow ${{ matrix.subworkflow }}
        run: nf-core subworkflows lint ${{ matrix.subworkflow }}

  # Next step (last step in this workflow)
  confirm-pass-lint:
    # again self-hosted machine. Discuss it
    runs-on:
      - runs-on=${{ github.run_id }}-confirm-pass-lint
      - runner=2cpu-linux-x64
      - image=ubuntu22-full-x64
    needs: [nf-core-lint-modules, nf-core-lint-subworkflows]
    if: always()

    # Generally just to check if something failed or not
    steps:
      - name: All tests ok
        if: ${{ success() || !contains(needs.*.result, 'failure') }}
        run: exit 0
      - name: One or more tests failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: debug-print
        if: always()
        run: |
          echo "toJSON(needs) = ${{ toJSON(needs) }}"
          echo "toJSON(needs.*.result) = ${{ toJSON(needs.*.result) }}"
